import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import image1 from "../images/section2-image1.png";
import image2 from "../images/section2-image2.png";
import image3 from "../images/section2-image3.png";
import image4 from "../images/section2-image4.png";
import image5 from "../images/Rectangle 537.png";
import image6 from "../images/section2-image5.png";
import styles from "../styles/index.module.css";

import VideoPage from "./VideoPage";

export default function Home() {
  return (
    <div className={styles.container} style={{ overflowX: "hidden" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.section1}>
        {/* <Image src={placeholder} className={styles.video} /> */}
        <VideoPage />
      </section>
      <section className={styles.section2}>
        <div className={styles.gallery}>
          <Image src={image1} className={styles.image1} />

          <Image src={image2} className={styles.image2} />

          <Image src={image3} className={styles.image3} />

          <Image src={image4} className={styles.image4} />

          <Image src={image5} className={styles.image5} />

          <Image src={image6} className={styles.image6} />

          <p className={styles.text}>
            Creating perfect{" "}
            <span className={styles.shortText}>lines and imposing</span>{" "}
            <span className={styles.shortText}>presence</span>
          </p>
        </div>
      </section>
    </div>
  );
}
